#  
# Thibautg16/UtilisateurBundle/Controller/UtilisateurController.php;
#
# Copyright 2015 GILLARDEAU Thibaut (aka Thibautg16)
#
# Authors :
#  - Gillardeau Thibaut (aka Thibautg16)
#

login:
    path:   /login
    defaults:  { _controller: Thibautg16UtilisateurBundle:Security:login }

login_check:
    path:  /login_check

logout:
    path:   /logout
 
thibautg16_utilisateur_homepage:
    path:     /utilisateur/lister
    defaults: { _controller: Thibautg16UtilisateurBundle:Utilisateur:lister}

thibautg16_utilisateur_lister:
    path:  /utilisateur/lister
    defaults: { _controller: Thibautg16UtilisateurBundle:Utilisateur:lister}

thibautg16_utilisateur_ajouter:
    path:  /utilisateur/ajouter
    defaults: { _controller: Thibautg16UtilisateurBundle:Utilisateur:ajouter}

thibautg16_utilisateur_modifier:
    path:  /utilisateur/modifier/{idUtilisateur}
    defaults: { _controller: Thibautg16UtilisateurBundle:Utilisateur:modifier}

thibautg16_utilisateur_supprimer:
    path:  /utilisateur/supprimer/{idUtilisateur}
    defaults: { _controller: Thibautg16UtilisateurBundle:Utilisateur:supprimer}

thibautg16_groupe_liste:
    path:  /groupe/lister
    defaults: { _controller: Thibautg16UtilisateurBundle:Groupe:liste}
    
thibautg16_groupe_ajouter:
    path:  /groupe/ajouter
    defaults: { _controller: Thibautg16UtilisateurBundle:Groupe:ajouter}
        
thibautg16_groupe_modifier:
    path:  /groupe/modifier/{idGroupe}
    defaults: { _controller: Thibautg16UtilisateurBundle:Groupe:modifier}

thibautg16_groupe_supprimer:
    path:  /groupe/supprimer/{idGroupe}
    defaults: { _controller: Thibautg16UtilisateurBundle:Groupe:supprimer}

thibautg16_role_lister:
    path:  /role/liste
    defaults: { _controller: Thibautg16UtilisateurBundle:Role:lister}

thibautg16_role_ajouter:
    path:  /role/ajouter
    defaults: { _controller: Thibautg16UtilisateurBundle:Role:ajouter}
        
thibautg16_role_modifier:
    path:  /role/modifier/{idRole}
    defaults: { _controller: Thibautg16UtilisateurBundle:Role:modifier}

thibautg16_role_supprimer:
    path:  /role/supprimer/{idRole}
    defaults: { _controller: Thibautg16UtilisateurBundle:Role:supprimer}